VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Brains"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public Sub Initialize(roLevel As Level, roActor As Actor2)
'Brain Dead
End Sub

Public Sub ResetState()
'Brain Dead
End Sub

Public Sub UpdateState()
'Brain Dead
End Sub

Public Sub Terminate()
'Brain Dead
End Sub
