VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "PlayerInput"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public bShieldsRequested As Boolean
Public bMissleRequested As Boolean
Public bMoveLeftRequested As Boolean
Public bMoveRightRequested As Boolean
Public bStopMoveRequested As Boolean
